---

- name: nginx install - Install nginx (Debian)
  ansible.builtin.apt:
    pkg:
      - nginx
    state: latest
    update_cache: true
  notify: nginx reload
  when: ansible_facts['os_family'] == 'Debian'

- name: nginx install - Install nginx (RedHat)
  ansible.builtin.dnf:
    name:  nginx
    state: latest
  notify: nginx reload
  when: ansible_facts['os_family'] == 'RedHat'
