---

- name: haproxy install - Install haproxy (Debian)
  ansible.builtin.apt:
    pkg:
      - haproxy
    state: latest
    update_cache: true
  notify: haproxy restart
  when: ansible_facts['os_family'] == 'Debian'

- name: haproxy install - Install haproxy (RedHat)
  ansible.builtin.dnf:
    name:  haproxy
    state: latest
  notify: haproxy restart
  when: ansible_facts['os_family'] == 'RedHat'
