---
- name: packages - install foreman installer and dependencies
  ansible.builtin.dnf:
    name:
      - foreman-installer-katello
      - openvox-server
      - foreman-proxy
      - scap-security-guide
    state: present
