---

- name: keycloak main - Validate variables
  ansible.builtin.import_tasks: preflight.yml

- name: keycloak main - Install (Docker)
  ansible.builtin.import_tasks: install-docker.yml
  when: keycloak_install_method == 'docker'

- name: keycloak main - Install (native)
  ansible.builtin.import_tasks: install-native.yml
  when: keycloak_install_method == 'native'
