---

- name: pdns_records main - Preflight validation
  import_tasks: preflight.yml

- name: pdns_records main - Manage zones
  import_tasks: zones.yml

- name: pdns_records main - Manage records
  import_tasks: records.yml
