---

- name: k8s debian-repos - Download Kubernetes release key (Debian)
  ansible.builtin.get_url:
    url:  "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc
    mode: "0644"

- name: k8s debian-repos - Add Kubernetes apt repository (Debian)
  ansible.builtin.apt_repository:
    repo:         "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    filename:     kubernetes
    state:        present
    update_cache: true

- name: k8s debian-repos - Install Kubernetes packages (Debian)
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state:        present
    update_cache: true

- name: k8s debian-repos - Enable kubelet (Debian)
  ansible.builtin.service:
    name:    kubelet
    enabled: true
