---

- name: k8s el-repos - Deploy Kubernetes repo file (RedHat)
  ansible.builtin.template:
    src:   el-repos_k8s.repo.j2
    dest:  /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode:  "0644"
  notify: k8s dnf clean

- name: k8s el-repos - Flush handlers to refresh repo metadata
  ansible.builtin.meta: flush_handlers

- name: k8s el-repos - Install Kubernetes packages (RedHat)
  ansible.builtin.dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state:            present
    disable_excludes: kubernetes
