---

- name: k8s initialize - Check if cluster is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: _k8s_admin_conf

- name: k8s initialize - Ensure container runtime is running
  ansible.builtin.systemd_service:
    name:    "{{ _k8s_runtime_service[k8s_container_runtime] }}"
    state:   started
    enabled: true
  vars:
    _k8s_runtime_service:
      cri-o:  crio.service
      docker: docker.service
      podman: podman.socket

- name: k8s initialize - Deploy kubeadm init config
  ansible.builtin.template:
    src: k8s-initconfig.yml.j2
    dest: /root/k8s-initconfig.yml
    owner: root
    group: root
    mode: "0600"

- name: k8s initialize - Initialize cluster
  ansible.builtin.command:
    cmd: kubeadm init --config /root/k8s-initconfig.yml
  vars:
    ansible_command_timeout: 1800
  when: not _k8s_admin_conf.stat.exists
  register: _k8s_initialized

- name: k8s initialize - Deploy Calico CNI
  ansible.builtin.shell: |
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ k8s_calico_version }}/manifests/operator-crds.yaml
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ k8s_calico_version }}/manifests/tigera-operator.yaml
    curl https://raw.githubusercontent.com/projectcalico/calico/v{{ k8s_calico_version }}/manifests/custom-resources.yaml \
      | sed -e "/cidr\:/s/192.168.0.0\/16/{{ k8s_pod_cidr | regex_replace('/', '\\/') }}/" \
            -e "/blockSize/s/[0-9]\{1,2\}/24/" \
      > /root/calico_config.yml
    kubectl apply -f /root/calico_config.yml
  when: _k8s_initialized.changed
