---

- name: ups_shed install - Install ansible-core + jq (Debian)
  ansible.builtin.apt:
    pkg:
      - ansible-core
      - jq
      - curl
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'

- name: ups_shed install - Enable EPEL (RedHat)
  ansible.builtin.dnf:
    name:  epel-release
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: ups_shed install - Install ansible-core + jq (RedHat)
  ansible.builtin.dnf:
    name:
      - ansible-core
      - jq
      - curl
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: ups_shed install - Check for kubectl
  ansible.builtin.stat:
    path: /usr/local/bin/kubectl
  register: _ups_shed_kubectl

- name: ups_shed install - Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v1.35.3/bin/linux/{{ 'arm64' if ansible_facts['architecture'] in ['aarch64', 'arm64'] else 'amd64' }}/kubectl"
    dest: /usr/local/bin/kubectl
    mode: "0755"
  when: not _ups_shed_kubectl.stat.exists
