---
# handlers file for keepalived

- name: restart keepalived
  ansible.builtin.systemd_service:
    name:  keepalived.service
    state: restarted
    enabled: true

#- name: set password
#  ansible.builtin.copy:
#    content: "{{ keepalived_auth_passwd }}"
#    dest: "{{ keepalived_passwd_file }}"
#    owner: root
#    group: root
#    mode:  0600
    