---
galaxy_info:
  author: mgcdrd
  description: Installs Foreman + Katello via foreman-installer-katello
  role_name: foreman_install

  license: GPL-3.0-or-later
  min_ansible_version: '2.14'

  galaxy_tags:
    - mgcdrd

collections:
  - community.general
  - community.hashi_vault
