---

- name: pdns_phpipam main - Preflight validation
  import_tasks: preflight.yml

- name: pdns_phpipam main - Resolve secrets
  import_tasks: secrets.yml

- name: pdns_phpipam main - Create directory layout
  import_tasks: directories.yml

- name: pdns_phpipam main - Deploy configuration files
  import_tasks: config.yml

- name: pdns_phpipam main - Deploy stack
  import_tasks: deploy.yml
